import React from 'react';
import { Battery, Sun, Zap, Activity, Grid, Wind } from 'lucide-react';

export const CATEGORIES = [
    'Production Solaire',
    'Stockage Énergie',
    'Continuité de Service',
    'Instrumentation',
    'Domotique Médicale',
    'Optimisation Chauffage'
];

export const ECO_PRODUCTS = [
    {
        id: 'solar-battery-5kwh',
        name: 'Batterie Solaire EcoStore 5 kWh',
        category: 'Stockage Énergie',
        icon: <Battery className="w-6 h-6" />,
        image: '/assets/products/solar-battery.png',
        color: 'text-accent-mint',
        bg: 'bg-accent-mint/10',
        price: '4 200 TND',
        desc: 'Batterie lithium-ion haute densité pour stocker l\'énergie solaire excédentaire. Idéale pour les coupures STEG nocturnes.',
        features: ['Cycle de vie 6 000+ charges', 'Garantie 10 ans', 'Intégration GTB native'],
        badge: 'Populaire',
    },
    {
        id: 'solar-panel-400w',
        name: 'Panneau Solaire Monocristallin 400 W',
        category: 'Production Solaire',
        icon: <Sun className="w-6 h-6" />,
        image: '/assets/products/solar-panel.png',
        color: 'text-accent-amber',
        bg: 'bg-accent-amber/10',
        price: '380 TND / unité',
        desc: 'Panneau haute efficacité 22.1% pour toitures cliniques. Résistant aux chaleurs estivales tunisiennes (IEC 61215).',
        features: ['Rendement 22.1%', 'Certifié IEC 61730', 'Pose incluse (min 10 panneaux)'],
        badge: 'Bestseller',
    },
    {
        id: 'smart-occupancy-sensor',
        name: 'Capteur d\'Occupation Ultra-Précis',
        category: 'Domotique Médicale',
        icon: <Grid className="w-6 h-6" />,
        image: '/assets/products/occupancy-sensor.png',
        color: 'text-accent-cyan',
        bg: 'bg-accent-cyan/10',
        price: '145 TND',
        desc: 'Détecte la présence humaine par micro-mouvements. Éteint automatiquement éclairage et climatisation en zone vide.',
        features: ['Détection PIR + US', 'Temporisation programmable', 'IP44 - Zones humides'],
        badge: 'Nouveau',
    },
    {
        id: 'thermostatic-valve',
        name: 'Vanne Thermostatique Connectée Zigbee',
        category: 'Optimisation Chauffage',
        icon: <Wind className="w-6 h-6" />,
        image: '/assets/products/thermostatic-valve.png',
        color: 'text-accent-sage',
        bg: 'bg-accent-sage/10',
        price: '210 TND',
        desc: 'Contrôle précis de la température radiateur par radiateur. Économise jusqu\'à 30% sur le chauffage central.',
        features: ['Compatibilité universelle', 'Mode hors-gel automatique', 'Autonomie pile 2 ans'],
        badge: 'Économe',
    },
    {
        id: 'backup-ups-20kva',
        name: 'Onduleur de Secours UPS 20 kVA',
        category: 'Continuité de Service',
        icon: <Zap className="w-6 h-6" />,
        image: '/assets/products/backup-ups.png',
        color: 'text-accent-cyan',
        bg: 'bg-accent-cyan/10',
        price: '8 900 TND',
        desc: 'Onduleur triphasé pour protéger vos équipements médicaux critiques. Bascule automatique en moins de 4 ms.',
        features: ['Temps de bascule < 4 ms', 'Autonomie 30 min (pleine charge)', 'Compatible blocs opératoires'],
        badge: 'Médical',
    },
    {
        id: 'smart-meter-iot',
        name: 'Compteur Intelligent IoT EnergyOS',
        category: 'Instrumentation',
        icon: <Activity className="w-6 h-6" />,
        image: '/assets/products/smart-meter.png',
        color: 'text-accent-sage',
        bg: 'bg-accent-sage/10',
        price: '620 TND',
        desc: 'Compteur communicant Modbus/BACnet intégré nativement à EnergyOS. Relevé instantané de la consommation par zone.',
        features: ['Protocole Modbus + BACnet', 'Précision classe 0.5S', 'Installation 30 min'],
        badge: 'EnergyOS',
    },
];
